version: '3.8'

services:
  booking-service:
    container_name: booking
    build: ./
    ports:
      - "8082:8082"
    environment:
      POSTGRES_HOST: "postgres_dock"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "booking"
    networks:
      - global-network
  migrate:
    image: migrate/migrate
    networks:
      - global-network
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  
                "postgres://postgres:root@postgres_dock:5432/booking?sslmode=disable", 
                "up" ]
networks:
  global-network:
    external: true 